#!/bin/bash

# tleupdate
# K. Scott Tripp <ktripp@umich.edu>
# 19 July 2012

# See if a directory is passed to the script
while getopts ":d:" opt; do
	case $opt in
		d)
			DIR=$OPTARG
			;;
		\?)
			echo "Invalid option -$OPTARG" >&2
			;;
		:)
			echo "Option $OPTARG requires an argument" >&2
			;;
	esac
done

# for compatibility with older version of script
if [ -z $DIR ];
then
	DIR=~/Data/TLE
fi

TLE=tlex_master.txt

if [ -e $DIR/$TLE ]
then
	rm $DIR/$TLE.1
	mv $DIR/$TLE $DIR/$TLE.1
fi

cd $DIR
wget http://gs.engin.umich.edu/predictions/tlex_master.txt

if [ -e $DIR/$TLE ]
then
	echo "Download successful"
else
	echo "Download unsuccessful, restoring old file"
	mv $DIR/$TLE.1 $DIR/$TLE
fi
